[project]
name = "grandma-gcn"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Roman", email = "roman.lemontagner@gmail.com"},
]
dependencies = [
    "gcn-kafka>=0.3.3",
    "tomli>=2.0.2",
    "pytz>=2025.2",
]
requires-python = ">=3.12"
readme = "README.md"
license = { text = "CeCILL-C" }

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = true

[project.optional-dependencies]
test = [
    "pytest>=8.3.3",
    "pytest-mock>=3.14.0",
]