"""init

Revision ID: 44b49190c297
Revises:
Create Date: 2025-07-04 08:52:46.620850

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "44b49190c297"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("gw_alerts")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gw_alerts",
        sa.Column("triggerId", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("thread_ts", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("triggerId", name=op.f("gw_alerts_pkey")),
    )
    # ### end Alembic commands ###
