"""migration_1

Revision ID: 79b89c014192
Revises:
Create Date: 2025-07-10 13:37:00.303827

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "79b89c014192"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gw_alerts",
        sa.Column("id_gw", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("triggerId", sa.String(), nullable=True),
        sa.Column("thread_ts", sa.String(), nullable=True),
        sa.Column("reception_count", sa.Integer(), nullable=False),
        sa.Column("payload_json", sa.JSON(), nullable=True),
        sa.Column("message_ts", sa.String(), nullable=True),
        sa.Column("is_process_running", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id_gw"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("gw_alerts")
    # ### end Alembic commands ###
