"""initial

Revision ID: c9dd00d9719c
Revises:
Create Date: 2025-07-04 14:50:41.225155

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c9dd00d9719c"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gw_alerts",
        sa.Column("triggerId", sa.String(), nullable=False),
        sa.Column("thread_ts", sa.String(), nullable=True),
        sa.Column("reception_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("triggerId"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("gw_alerts")
    # ### end Alembic commands ###
